# Generated by Django 5.1.5 on 2025-01-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=80, null=True)),
                ('mobile', models.IntegerField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
