# Generated by Django 5.1.5 on 2025-02-05 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('house_no', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('road_no', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('landmark', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('total_price', models.IntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
